-- 포인트 지갑 (회원 단위 Aggregate Root)
CREATE TABLE point_wallet (
    member_id BIGINT NOT NULL,
    CONSTRAINT pk_point_wallet PRIMARY KEY (member_id)
);

-- 적립 포인트 (지갑 1:N)
CREATE TABLE earned_point (
    earned_point_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id         BIGINT       NOT NULL,
    amount            INT          NOT NULL,
    remaining_amount  INT          NOT NULL,
    expire_at         TIMESTAMP    NOT NULL,
    source_type       VARCHAR(30)  NOT NULL,
    status            VARCHAR(30)  NOT NULL,
    created_at        TIMESTAMP    NOT NULL,
    updated_at        TIMESTAMP    NOT NULL,

    CONSTRAINT pk_earned_point PRIMARY KEY (earned_point_id),
    CONSTRAINT fk_earned_point_wallet
    FOREIGN KEY (member_id)
    REFERENCES point_wallet (member_id)
);

-- 포인트 사용 이력 (한 번의 사용)
CREATE TABLE point_usage (
    usage_id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id   BIGINT       NOT NULL,
    order_no    VARCHAR(100) NOT NULL,
    used_amount INT          NOT NULL,
    created_at  TIMESTAMP    NOT NULL,

    CONSTRAINT pk_point_usage PRIMARY KEY (usage_id)
    -- 필요하면 여기서 member_id FK 를 걸 수도 있음
    -- , CONSTRAINT fk_point_usage_wallet
    -- FOREIGN KEY (member_id) REFERENCES point_wallet (member_id)
);

-- 포인트 사용 상세 (어떤 적립에서 얼마를 깎았는지)
CREATE TABLE point_usage_detail (
    usage_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usage_id        BIGINT NOT NULL,
    earned_point_id BIGINT NOT NULL,
    amount          INT    NOT NULL,

    CONSTRAINT pk_point_usage_detail PRIMARY KEY (usage_detail_id),

    CONSTRAINT fk_point_usage_detail_usage
    FOREIGN KEY (usage_id)
    REFERENCES point_usage (usage_id),

    CONSTRAINT fk_point_usage_detail_earned
    FOREIGN KEY (earned_point_id)
    REFERENCES earned_point (earned_point_id)
);

-- 정책
CREATE TABLE point_policy (
  policy_id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  max_earn_per_txn    INT      NOT NULL,
  max_balance         INT      NOT NULL,
  updated_at          TIMESTAMP NOT NULL,

  CONSTRAINT pk_point_policy PRIMARY KEY (policy_id)
);

-- 조회/조인 최적화를 위한 인덱스들 (옵션이지만 강추)
CREATE INDEX idx_earned_point_member
    ON earned_point (member_id);

CREATE INDEX idx_point_usage_member
    ON point_usage (member_id);

CREATE INDEX idx_point_usage_detail_usage
    ON point_usage_detail (usage_id);

CREATE INDEX idx_point_usage_detail_earned
    ON point_usage_detail (earned_point_id);

CREATE INDEX idx_point_policy
    ON point_policy (policy_id);

